var datasource_2008 = {
	"va": [
		{"year": "2008", "category": "Visual Arts", "shortcat": "va", "title": "(205) Normal Mapping Industry Survey", "media": "slider", "sid": "181", "spage": "https://www.gdcvault.com/play/181", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6526i1.pdf", "speaker": "Ricardo Ariza, Steve Chapman, Richard Diamant, Adam Myhill, Gio Nakpil, Scott Spencer, Alex Velasquez", "company": "Naughty Dog, Gentle Giant Studios, Naughty Dog Inc., Pandemic Studios, Freedom of Teach, Gentle Giant Studios, Raven Software", "overview": null}
	],
	"de": [
		{"year": "2008", "category": "Game Design", "shortcat": "de", "title": "Teaching Players: Tutorial and Opening Mission Design for COMPANY OF HEROES", "media": "slider", "sid": "278", "spage": "https://www.gdcvault.com/play/278", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6529i1.pdf", "speaker": "Neil Jones-Rodway, Aldric Sun", "company": "Relic Entertain..., Relic Entertain...", "overview": null},
		{"year": "2008", "category": "Game Design", "shortcat": "de", "title": "Game Studies Download 3.0", "media": "slider", "sid": "195", "spage": "https://www.gdcvault.com/play/195", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6207i1.pdf", "speaker": "Ian Bogost, Mia Consalvo, Jane McGonigal", "company": "The Georgia Institute of Technology, MIT, Comparative Media Studies, Social Chocolate", "overview": null},
		{"year": "2008", "category": "Game Design", "shortcat": "de", "title": "Game Design Based on Micro-Transactions in Online Games", "media": "slider", "sid": "213", "spage": "https://www.gdcvault.com/play/213", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6981i1.pdf", "speaker": "Gyuhwan Oh, Taiyoung Ryu", "company": "Ajou University, University of Southern California", "overview": null},
		{"year": "2008", "category": "Game Design", "shortcat": "de", "title": "CRYSIS in the Making", "media": "slider", "sid": "201", "spage": "https://www.gdcvault.com/play/201", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6465i1.pdf", "speaker": "Bernd Diemer, Sten Huebler, Cevat Yerli", "company": "Crytek Hungary, Crytek GmbH, Crytek", "overview": null},
		{"year": "2008", "category": "Game Design", "shortcat": "de", "title": "A PORTAL Post-Mortem: Integrating Writing and Design", "media": "slider", "sid": "197", "spage": "https://www.gdcvault.com/play/197", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6422i1.pdf", "speaker": "Kim Swift, Erik Wolpaw", "company": "Airtight Games, Valve", "overview": null},
		{"year": "2008", "category": "Game Design", "shortcat": "de", "title": "10 Tips for a Successful Wiki", "media": "slider", "sid": "196", "spage": "https://www.gdcvault.com/play/196", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6348i1.pdf", "speaker": "James Everett", "company": "", "overview": null},
		{"year": "2008", "category": "Game Design", "shortcat": "de", "title": "10 in 20: Ten Keys to Designing for IPs", "media": "slider", "sid": "183", "spage": "https://www.gdcvault.com/play/183", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6147i1.pdf", "speaker": "Timothy Longo", "company": "Crystal Dynamics", "overview": null},
		{"year": "2008", "category": "Game Design", "shortcat": "de", "title": "The Emergent Gamer", "media": "video", "vid": "27", "vpage": "https://www.gdcvault.com/play/27", "vdownload": "https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc08/video/emergentgamer.flv", "speaker": "Rod Humble", "company": "Electronic Arts", "overview": ""},
		{"year": "2008", "category": "Game Design", "shortcat": "de", "title": "FABLE 2 - The Big Three Features Revealed", "media": "video", "vid": "28", "vpage": "https://www.gdcvault.com/play/28", "vdownload": "https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc08/video/fable2.flv", "speaker": "Peter Molyneux", "company": "Lionhead Studios", "overview": ""},
		{"year": "2008", "category": "Game Design", "shortcat": "de", "title": "Metaplace Postmortem: Reinventing MMOs", "media": "video", "vid": "34", "vpage": "https://www.gdcvault.com/play/34", "vdownload": "https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc08/video/metaplacepostmortem.flv", "speaker": "Raph Koster, Sean Riley", "company": "Playdom, Metaplace", "overview": ""},
		{"year": "2008", "category": "Game Design", "shortcat": "de", "title": "How to Create an Industry: The Making of the Brown Box and PONG", "media": "video", "vid": "29", "vpage": "https://www.gdcvault.com/play/29", "vdownload": "https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc08/video/howtocreateanindustry.flv", "speaker": "Allan Alcorn, Ralph H. Baer", "company": "IMMI,", "overview": ""},
		{"year": "2008", "category": "Game Design", "shortcat": "de", "title": "Creating Spielberg's BOOM BLOX", "media": "video", "vid": "36", "vpage": "https://www.gdcvault.com/play/36", "vdownload": "https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc08/video/speilbergsboomblox.flv", "speaker": "Louis Castle", "company": "InstantAction", "overview": ""}
	],
	"pg": [
		{"year": "2008", "category": "Programming", "shortcat": "pg", "title": "Stylization with a Purpose: The Illustrative World of TEAM FORTRESS 2", "media": "slider", "sid": "279", "spage": "https://www.gdcvault.com/play/279", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6543i1.pdf", "speaker": "Jason Mitchell", "company": "Valve Software", "overview": null},
		{"year": "2008", "category": "Programming", "shortcat": "pg", "title": "Stupid Spherical Harmonics (SH) Tricks", "media": "slider", "sid": "273", "spage": "https://www.gdcvault.com/play/273", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6469i1.pdf", "speaker": "Peter-Pike Sloan", "company": "Microsoft", "overview": null},
		{"year": "2008", "category": "Programming", "shortcat": "pg", "title": "Lighting and Material of HALO 3", "media": "slider", "sid": "253", "spage": "https://www.gdcvault.com/play/253", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6220i1.pdf", "speaker": "Hao Chen", "company": "Bungie Studios", "overview": null},
		{"year": "2008", "category": "Programming", "shortcat": "pg", "title": "How to Go from PC to Console Development without Shooting Yourself in the Foot", "media": "slider", "sid": "249", "spage": "https://www.gdcvault.com/play/249", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6212i1.pdf", "speaker": "Elan Ruskin", "company": "Valve", "overview": null},
		{"year": "2008", "category": "Programming", "shortcat": "pg", "title": "Fast Water Simulation for Games Using Height Fields", "media": "slider", "sid": "203", "spage": "https://www.gdcvault.com/play/203", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6509i1.pdf", "speaker": "Matthias M\u00c3\u00bcller-Fischer", "company": "AGEIA", "overview": null},
		{"year": "2008", "category": "Programming", "shortcat": "pg", "title": "Designing and Implementing a Dynamic Camera System", "media": "slider", "sid": "192", "spage": "https://www.gdcvault.com/play/192", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6174i1.pdf", "speaker": "Phil Wilkins", "company": "SCEA Santa Monica", "overview": null},
		{"year": "2008", "category": "Programming", "shortcat": "pg", "title": "CRYSIS Next-Gen Effects", "media": "slider", "sid": "247", "spage": "https://www.gdcvault.com/play/247", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6172i1.pdf", "speaker": "Tiago Sousa", "company": "Crytek", "overview": null},
		{"year": "2008", "category": "Programming", "shortcat": "pg", "title": "Creating a Character in DRAKE'S FORTUNE", "media": "slider", "sid": "190", "spage": "https://www.gdcvault.com/play/190", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6169i1.pdf", "speaker": "Christian Gyrling", "company": "Naughty Dog Inc.", "overview": null},
		{"year": "2008", "category": "Programming", "shortcat": "pg", "title": "Adventures in Data Compilation and Scripting for UNCHARTED: DRAKE'S FORTUNE", "media": "slider", "sid": "211", "spage": "https://www.gdcvault.com/play/211", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6636i1.pdf", "speaker": "Dan Liebgold", "company": "Naughty Dog, Inc.", "overview": null},
		{"year": "2008", "category": "Programming", "shortcat": "pg", "title": "(103) Advanced Visual Effects with Direct3D", "media": "slider", "sid": "185", "spage": "https://www.gdcvault.com/play/185", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6152i1.pdf", "speaker": "Louis Bavoil, Chas Boyd, Cem Cebenoyan, Holger Gruen, Richard Huddy, Ignacio Llamas, Natalya Tatarchuk, Andrei Tatarinov, Nicolas Thibieroz, Alex Vlachos", "company": "NVIDIA, Microsoft, NVIDIA, AMD GmbH, AMD, NVIDIA, AMD, NVIDIA, AMD, Valve", "overview": null}
	],
	"pr": [
		{"year": "2008", "category": "Production", "shortcat": "pr", "title": "Outsourcing: Best Practices at Pandemic Studios", "media": "slider", "sid": "276", "spage": "https://www.gdcvault.com/play/276", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6525i1.pdf", "speaker": "Carey Chico", "company": "GlobeX Studios LA Inc", "overview": null}
	],
	"au": [
		{"year": "2008", "category": "Audio", "shortcat": "au", "title": "Automatic Audio in Frostbite", "media": "slider", "sid": "187", "spage": "https://www.gdcvault.com/play/187", "sdownload": "https://media.gdcvault.com/gdc08/slides/S6159i1.pdf", "speaker": "David Mollerstedt, Stefan Strandberg", "company": "EA Digital Illusions CE AB, Digital Illusions CE AB", "overview": null}
	],
	"bm": [
		{"year": "2008", "category": "Business and Management", "shortcat": "bm", "title": "(307) Independent Games Summit", "media": "video", "vid": "30", "vpage": "https://www.gdcvault.com/play/30", "vdownload": "https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc08/video/evolvingaquaria.flv", "speaker": "Thomas Arundel, Vicky Arundel, John Beck, Jonathan Blow, Matt Bozon, Raigan Burns, Tom Buscaglia, Jamie Cheng, Ryan Clark, N\\'Gai Croal, Dylan Cuthbert, Bill Dugan, Brent Fox, Tracy Fullerton, Kyle Gabler, Kyle Gray, Alec Holowka, Chris Hughes, Arthur K Humphrey, Pekko Koskinen, Joseph Lieberman, Noel Llopis, Jonathan Mak, Mark Morris, Chris Pasley, Kellee Santiago, Mare Sheppard, Steve Swink, Steve Taylor, Stephen Totilo, Jacob Van Wingen, Nick Waanders, Matthew Wegner, Josh Williams, Derek Yu", "company": "Introversion, Introversion Software, WayForward Technologies, Number None, Inc., WayForward, , Dev Biz, Inc., Klei Entertainment, Grubby Games Inc., Hit Detection, Q - Games, Torpex Games, Wahoo Studios / NinjaBee, USC School of Cinematic Arts, 2D Boy, Tomorrow Corporation, Infinite Ammo, FlashGame..., Last Day of Work, Playsign, Arcade Town, Snappy Touch, Queasy Games, Introversion Software, Kongregate, thatgamecompany, Metanet Software, Enemy Airship, Wahoo Studios / NinjaBee, MTV News, Gastronaut Studios LLC, Slick Entertainment, Flashbang Studios, Alamofire, Independent", "overview": ""},
		{"year": "2008", "category": "Business and Management", "shortcat": "bm", "title": "(305) Serious Games Summit", "media": "video", "vid": "35", "vpage": "https://www.gdcvault.com/play/35", "vdownload": "https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc08/video/seriousworldreport.flv", "speaker": "Akira Baba, Ian Bogost, Randy Brown, Li-Te Cheng, Don Daglow, Stephane de Buttet, Donna Djordjevich, Noah Falstein, Shawn Firminger, Tracy Fullerton, Alex Games, Amulya K. Garga, Wendy Goldner, Nobushige Hichibe, Tim Holt, Bob Hone, Frank Lantz, Perry McDowell, Rob Moore, Robert Musson, John Nordlinger, Nora Paul, Steven Rohall, Katie Salen, Ben Sawyer, David T. Schaller, Wolf Schuster, Steve Seabolt, Lori Shyba, Roger Smith, Robert J. Stone, Chris Swain, Shinsuke Tomiyasu, Greg Trefry, Swen Vincke, Richard Wainess, Eric Zimmerman", "company": "University of Tokyo, The Georgia Institute of Technology, Virtual Heroes Inc., IBM, Don Daglow Interactive Entertainment, Simlinx, Sandia National Labs, The Inspiracy, ACES Studio - Microsoft Game Studios, USC School of Cinematic Arts, University of Wisconsin..., Lockheed Martin, The Wild Divine Project, The University of Tokyo, Past4Ward, Red Hill Studios, Area/Code/Zynga, Delta3D, Electronic Arts - Tiburon, Microsoft, Microsoft, University of Minnesota, IBM Collabora... User Experience Research Group, Parsons School of Design, Digitalmill, eduweb, Red Hill Studios, Electronic Arts, Sundial Media, US Army Simulation and Training, UK Human Factors Integration Defense Tech. Center, University of Southern California, University of Tokyo, Gamelab, Larian Studios, University of Southern California, Independent", "overview": ""},
		{"year": "2008", "category": "Business and Management", "shortcat": "bm", "title": "(303) Casual Games Summit", "media": "video", "vid": "31", "vpage": "https://www.gdcvault.com/play/31", "vdownload": "https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc08/video/theyearincasualgames.flv", "speaker": "Ed Allard, Ellen Guon Beeman, Joel Brodie, Kate Connally, Kenny Shea Dinkin, Chris Early, Nick Fortugno, David Fox, Juan Gril, James Gwertzman, Chris Houtzer, Arthur K Humphrey, Daniel James, Todd Kerpelman, Steve Meretzky, David Rohrl, Dean Takahashi, Margaret Wallace, John Welch, Patrick Wylie, Gabe Zichermann, Eric Zimmerman", "company": "PopCap Games, Xbox LIVE Arcade, Gamezebo, MTV Networks, Independent, MS/Windows Gaming, Playmatics, iWin, Joju Games, PopCap Games, Inc., RealNetworks Inc., Last Day of Work, Three Rings, EA/Pogo, Playdom, Playdom, VentureBeat, Playmatics, Making Fun, Big Fish Games Studios, Independent, Independent", "overview": ""}
	]
}