var datasource_2006 = {
	"bm": [
		{"year": "2006", "category": "Business and Management", "shortcat": "bm", "title": "Profitable Growth \u2013 The $ and Cents of Growing a Healthy Studio", "media": "slider", "sid": "1013439", "spage": "https://www.gdcvault.com/play/1013439", "sdownload": "https://media.gdcvault.com/gdc06/slides/S1607i1.pdf", "speaker": "Guha Bala, Karthik Bala", "company": "Vicarious Visions, Inc., VICARIOUS VISIONS", "overview": "A healthy studio is more than just fast code, and cool shaders.  Its a \ndemanding business with customers, cash flows, and creditors.  Sustainable, \nprofitable growth comes from great sales, marketing, human resources, and \nfinance in addition to product development.  A set of financial tools for game \ndevelopment can lead to some of the best decisions a studio can make for \nproducts, people, and customers.  In this lecture we look at the dollars and \ncents of it all, and how to design financial management tools that will help \nyou build a great studio."},
		{"year": "2006", "category": "Business and Management", "shortcat": "bm", "title": "Brand Development for Video Games", "media": "slider", "sid": "1013469", "spage": "https://www.gdcvault.com/play/1013469", "sdownload": "https://media.gdcvault.com/gdc06/slides/S2429i1.pdf", "speaker": "Oliver Wright", "company": "SCEE", "overview": "Effective branding is a vital component in creating a successful videogame today. The visual identity of a game is generally the consumers first impression, and as such must convey a lot of information about the product and why they should buy it. In order to ensure a high quality product, the identity needs to be reinforced throughout the game, from packaging through menus to end credits. At its best, the visual identity can be simplified to a single iconic statement which is instantly recognizable and attracts the intended audience."}
	],
	"pg": [
		{"year": "2006", "category": "Programming", "shortcat": "pg", "title": "High Performance Physics Solver Design for Next Generation Consoles", "media": "slider", "sid": "1013474", "spage": "https://www.gdcvault.com/play/1013474", "sdownload": "https://media.gdcvault.com/gdc06/slides/S2714i1.pdf", "speaker": "Vangelis Kokkevis", "company": "Google", "overview": "This presentation guides developers though the unique code and data design considerations required to build high-performance game engine components for the next generation console hardware.  Using examples from specific physics solvers such as fluids, cloth, rigid and articulated bodies, it highlights the necessary steps for designing and implementing efficient code that makes full use of the\nhardware's impressive potential."},
		{"year": "2006", "category": "Programming", "shortcat": "pg", "title": "Crowd Simulation on PS3", "media": "slider", "sid": "1013476", "spage": "https://www.gdcvault.com/play/1013476", "sdownload": "https://media.gdcvault.com/gdc06/slides/S2769i1.pdf", "speaker": "Craig Reynolds", "company": "Sony Computer Entertainment America", "overview": "Crowds and other forms of flock-like group motion are modeled with interacting particle systems.  These multi-agent simulations are computationally expensive because each agent must identify its nearest neighbors.  Time to run the simple implementation grows as the square of the number of agents, so large groups can be prohibitively expensive.  This lecture will describe experiments running crowd/flock simulations with thousands of individuals at 60 frames per second on the PLAYSTATION3.  It will discuss how a traditional crowd system can be recast to map efficiently onto the Cell architecture of the PS3.  The lecture will include implementation details and live demos will be shown."},
		{"year": "2006", "category": "Programming", "shortcat": "pg", "title": "Best Practices for Game Development", "media": "slider", "sid": "1013466", "spage": "https://www.gdcvault.com/play/1013466", "sdownload": "https://media.gdcvault.com/gdc06/slides/S2403i1.pdf", "speaker": "Grady Booch", "company": "IBM", "overview": "In game development, software complexity has reached a critical mass, the artistic element has spiked, and for both domains, reuse is minimal. The game community is experiencing issues that other software-intensive domains have passed through and will benefit from drawing upon best practices in defense, embedded, and enterprise systems. We will examine best practices and application to game development."}
	],
	"au": [
		{"year": "2006", "category": "Audio", "shortcat": "au", "title": "Backwards Is Forward: Making Better Games with Test-Driven Development", "media": "slider", "sid": "1013416", "spage": "https://www.gdcvault.com/play/1013416", "sdownload": "https://media.gdcvault.com/gdc06/slides/S1528i1.pdf", "speaker": "Sean Houghton, Sean Houghton, Sean Houghton, Sean Houghton, Noel Llopis, Noel Llopis, Noel Llopis, Noel Llopis", "company": ", High Moon Studios, , , , Snappy Touch, ,", "overview": "Test-Driven Development (TDD) is a relatively new technique that, despite gathering a lot of momentum, has made very few inroads in our industry. However, this is a technique that is too useful to overlook any longer. In an industry where we're constantly pushing the boundaries and exploring the unknown, the benefits of TDD are a very good match for many of our development problems.\r\n\r\nDeveloping software with TDD might seem backwards at first glance: First a short unit test is written, then the code to make that unit test pass is implemented, and finally the code can be refactored (without changing its functionality). At that point, the cycle is repeated over and over, always starting with a unit test. The cycle itself should be short, in the order of a couple of minutes and all of the tests are required to run before moving forward.\r\n\r\nTDD has some very interesting consequences: It creates a safety net of unit tests, which allows for major refactorings  or introducing new features late in development without fear of breaking existing code, it forces the developer to use his own code first, so it is always written from the point of view of the user of the code, it encourages more modular, simpler code that can be easily modified and reused, and it serves as a form of documentation that, unlike comments or documents, can never get out of date. Last but not least, it provides the developer with instant feedback, building his confidence in the code and even making the programming experience much more enjoyable.\r\n\r\nThe talk starts with a general overview of TDD, followed by a detailed explanation of how to put it into practice, and a live TDD demonstration implementing a high-level game task fully in TDD. The second half of the session is dedicated to some of the unique aspects of game development, such as having different hardware platforms, dealing with graphics, or using middleware and how they affect TDD. Finally, the session concludes with the lessons learned at High Moon Studios from using TDD in a variety of projects."},
		{"year": "2006", "category": "Audio", "shortcat": "au", "title": "Building a Better Battlestar", "media": "video", "vid": "1016689", "vpage": "https://www.gdcvault.com/play/1016689", "vdownload": "https://archive.org/download/2006-gdc-battle-star-galactica-keynote-camera-x-03-22-2006/2006%20GDC%20-%20Battle%20Star%20Galactica%20Keynote%20-%20Camera%20X%20-%2003-22-2006.mp4", "speaker": "Ronald Moore", "company": "", "overview": "Sequels and reboots in Hollywood have now become more common in gaming. In this \"vision track\" keynote, the creator and producer of the new Battlestar Galactica TV series discusses how he developed and adapted the existing story behind a large franchise into a new series."}
	],
	"va": [
		{"year": "2006", "category": "Visual Arts", "shortcat": "va", "title": "Advanced Tool Writing for Character Technical \rDirectors (TD)", "media": "slider", "sid": "1013414", "spage": "https://www.gdcvault.com/play/1013414", "sdownload": "https://media.gdcvault.com/gdc06/slides/S1510i1.pdf", "speaker": "Judd Simantov", "company": "Naughty Dog Inc", "overview": "This presentation teaches and explains not only how the API is \r\nused, but also how to write stable, clean tools that can easily be \r\nextended later. "}
	],
	"un": [
		{"year": "2006", "category": "Vision", "shortcat": "un", "title": "Disrupting Development", "media": "video", "vid": "1019910", "vpage": "https://www.gdcvault.com/play/1019910", "vdownload": "https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc06/video/2006-GDC-Nintendo Keynote03-23-2006.mp4", "speaker": "Satoru Iwata", "company": "Nintendo Co., Ltd.", "overview": "This year will see the arrival of more new portable and home game systems, and outside attention remains predictably focused on technical specifications and processing muscle. This is not trivial; but also not newsworthy. After all, every new system is more powerful than its predecessor. Developers know what drives the video game business. It is our work. We are the creators, the innovators, the entertainers. We understand that people who imagine things, even more than the people who engineer them, are the key to reaching players. Unfortunately, the application of imagination is getting more and more difficult. Larger games require more hours, more manpower, and a lot more money. And as budgets rise, the appetite for risk falls. As Nintendo has demonstrated with Nintendo DS, our goal is to expand the industry to new players - and to surprise existing players. In Distrupting Development, Nintendo President Satoru Iwata will reveal the backstory of how a string of recent desruptive products from Nintendo - the Nintendo DS, the \"brain-training\" games, and Nintendo WiFi Connection - surprised the market. He will shae his thoughts on the role the forthcoming Nintendo Revolution will play in the console world, and how he believes that, in the process, the possibilities for every game developer will be dramatically increased."}
	]
}